version: "2"
services:
  webserver:
    image: patrickbaber/website:latest
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/var/www"